# Это поддерживаемые модели финансирования платформ
github: [admin-Gomer]
patreon: # Заменять
open_collective: # Замените на одно открытое коллективное имя пользователя
ko_fi: # Замените на одно имя пользователя Kofi
tidelift: # Замените на единую платформу Tide lift-название платформы/название упаковки, например, npm/babel
community_bridge: # Замените на одно название проекта Community Bridge, например, cloud-foundry
liberapay: # Замените на одно имя пользователя Liberal pay
issuehunt: # Замените имя пользователя для поиска по одной проблеме
otechie: # Замените на одно имя пользователя технаря
custom: ['https://dash.skyultraplus.com', 'https://boxmineworld.com']
